# Generated by Django 6.1 on 2026-08-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
