"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(
    BASE_DIR / ".env",
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-_na@lew^wd#7!&79&@3@c_6e(ub%)(e9=^o-_e%)c9w*7bxsfp'

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
)

if not SECRET_KEY:

    raise ValueError(
        "SECRET_KEY is missing. Add it to your .env file.",
    )

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.environ.get(
    "DEBUG",
    "False",
) == "True"

#ALLOWED_HOSTS = []

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "",
    ).split(",")
    if host.strip()
]


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME",
)

if RENDER_EXTERNAL_HOSTNAME:

    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME,
    )

    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RENDER_EXTERNAL_HOSTNAME}",
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django.contrib.sites",
    "django.contrib.sitemaps",

    'blog',
    'accounts',
    'django_ckeditor_5',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

USE_POSTGRES = os.environ.get(
    "USE_POSTGRES",
    "False",
) == "True"


if USE_POSTGRES:

    POSTGRES_DB = os.environ.get(
        "POSTGRES_DB",
    )

    POSTGRES_USER = os.environ.get(
        "POSTGRES_USER",
    )

    POSTGRES_PASSWORD = os.environ.get(
        "POSTGRES_PASSWORD",
    )

    POSTGRES_HOST = os.environ.get(
        "POSTGRES_HOST",
        "127.0.0.1",
    )

    POSTGRES_PORT = os.environ.get(
        "POSTGRES_PORT",
        "5432",
    )

    if not all(
        [
            POSTGRES_DB,
            POSTGRES_USER,
            POSTGRES_PASSWORD,
        ]
    ):

        raise ValueError(
            "PostgreSQL settings are missing. Check POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD in .env.",
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
        }
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

#MAILERS = {
#    'default': {
#        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#    },
#}

EMAIL_MODE = os.environ.get(
    "EMAIL_MODE",
    "console",
)


if EMAIL_MODE == "smtp":

    SMTP_HOST = os.environ.get(
        "SMTP_HOST",
    )

    SMTP_PORT = int(
        os.environ.get(
            "SMTP_PORT",
            "587",
        )
    )

    SMTP_USERNAME = os.environ.get(
        "SMTP_USERNAME",
    )

    SMTP_PASSWORD = os.environ.get(
        "SMTP_PASSWORD",
    )

    SMTP_USE_TLS = os.environ.get(
        "SMTP_USE_TLS",
        "True",
    ) == "True"

    SMTP_USE_SSL = os.environ.get(
        "SMTP_USE_SSL",
        "False",
    ) == "True"

    if not SMTP_HOST:

        raise ValueError(
            "SMTP_HOST is missing. Add it to the environment variables.",
        )

    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": SMTP_HOST,
                "port": SMTP_PORT,
                "username": SMTP_USERNAME,
                "password": SMTP_PASSWORD,
                "use_tls": SMTP_USE_TLS,
                "use_ssl": SMTP_USE_SSL,
            },
        },
    }

else:

    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }

#DEFAULT_FROM_EMAIL = "noreply@myblog.local"

#CONTACT_EMAIL = "admin@myblog.local"

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "noreply@myblog.local",
)

CONTACT_EMAIL = os.environ.get(
    "CONTACT_EMAIL",
    DEFAULT_FROM_EMAIL,
)

USE_SECURE_PROXY_SSL_HEADER = os.environ.get(
    "USE_SECURE_PROXY_SSL_HEADER",
    "False",
) == "True"


if USE_SECURE_PROXY_SSL_HEADER:

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )


ENABLE_HTTPS_SECURITY = os.environ.get(
    "ENABLE_HTTPS_SECURITY",
    "False",
) == "True"


if ENABLE_HTTPS_SECURITY:

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

else:

    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

    SECURE_HSTS_SECONDS = 0

    SECURE_HSTS_INCLUDE_SUBDOMAINS = False

    SECURE_HSTS_PRELOAD = False



CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
            "insertTable",
            "imageUpload",
            "codeBlock",
            "|",
            "undo",
            "redo",
        ],
    },
}

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

CKEDITOR_5_UPLOAD_PATH = "uploads/"

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"
